# See the documentation for more information:
# https://packit.dev/docs/configuration/

upstream_project_url: https://github.com/nikromen/pyvem.git
specfile_path: pyvem.spec
downstream_package_name: pyvem
upstream_package_name: pyvem

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9

  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9

  - job: copr_build
    trigger: commit
    targets:
      - fedora-all
      - epel-9
    owner: "nikromen"
    project: "pyvem"
    branch: main
    list_on_homepage: True
    preserve_project: True
